/**
 * The permission catalog, client side.
 *
 * Keys are defined once in the database (`permission_registry`, seeded by
 * migration 0011) and mirrored here so call sites get autocompletion and a
 * compile error on a typo. The list below is generated from that table — when
 * a migration registers a new key, regenerate rather than hand-edit:
 *
 *   select key from permission_registry order by module, sort_order, key;
 *
 * Nothing breaks if this file falls behind: `has()` takes any string and the
 * server is the authority either way. The constants are ergonomics, not policy.
 */

export const PERM = {
  ATTENDANCE_VIEW_OWN: 'attendance.view_own',
  ATTENDANCE_VIEW_SCHEDULE: 'attendance.view_schedule',
  ATTENDANCE_CLOCK: 'attendance.clock',
  ATTENDANCE_SUBMIT_ENTRY: 'attendance.submit_entry',
  ATTENDANCE_APPROVE_ENTRY: 'attendance.approve_entry',
  ATTENDANCE_VIEW_OWN_PAY: 'attendance.view_own_pay',
  ATTENDANCE_VIEW_ALL: 'attendance.view_all',
  ATTENDANCE_EDIT_ENTRY: 'attendance.edit_entry',
  ATTENDANCE_MANUAL_ENTRY: 'attendance.manual_entry',
  ATTENDANCE_DELETE: 'attendance.delete',
  ATTENDANCE_MANAGE_CLOCK: 'attendance.manage_clock',
  ATTENDANCE_VIEW_PAY: 'attendance.view_pay',
  ATTENDANCE_MANAGE_PAY: 'attendance.manage_pay',
  ATTENDANCE_MANAGE_BONUS: 'attendance.manage_bonus',
  ATTENDANCE_SETTINGS: 'attendance.settings',
  ATTENDANCE_MANAGE_WAREHOUSES: 'attendance.manage_warehouses',
  ATTENDANCE_EXPORT: 'attendance.export',
  BOARD_VIEW: 'board.view',
  BOARD_VIEW_STAFFING: 'board.view_staffing',
  BOARD_INLINE_EDIT: 'board.inline_edit',
  BOARD_BULK_EDIT: 'board.bulk_edit',
  BOARD_EXPORT: 'board.export',
  BOARD_COLUMNS: 'board.columns',
  CALENDAR_VIEW: 'calendar.view',
  CALENDAR_DRAG: 'calendar.drag',
  CALENDAR_SAVE_FILTERS: 'calendar.save_filters',
  CONTRACTORS_VIEW: 'contractors.view',
  CONTRACTORS_CREATE: 'contractors.create',
  CONTRACTORS_EDIT: 'contractors.edit',
  CONTRACTORS_DELETE: 'contractors.delete',
  CONTRACTORS_RESTORE: 'contractors.restore',
  CONTRACTORS_MANAGE_WORKERS: 'contractors.manage_workers',
  CONTRACTORS_VIEW_PRICING: 'contractors.view_pricing',
  CONTRACTORS_EDIT_PRICING: 'contractors.edit_pricing',
  CONTRACTORS_MARK_PAID: 'contractors.mark_paid',
  CONTRACTORS_ASSIGN_WORKERS: 'contractors.assign_workers',
  CONTRACTORS_VIEW_CONTACT: 'contractors.view_contact',
  CONTRACTORS_EXPORT: 'contractors.export',
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_EDIT: 'customers.edit',
  CUSTOMERS_DELETE: 'customers.delete',
  CUSTOMERS_RESTORE: 'customers.restore',
  CUSTOMERS_VIEW_CONTACT: 'customers.view_contact',
  CUSTOMERS_EDIT_CONTACT: 'customers.edit_contact',
  CUSTOMERS_MANAGE_FORM_FIELDS: 'customers.manage_form_fields',
  CUSTOMERS_MANAGE_EXECUTION_METHODS: 'customers.manage_execution_methods',
  CUSTOMERS_MANAGE_SUPPLIERS: 'customers.manage_suppliers',
  CUSTOMERS_ALLOW_EVENT_CREATION: 'customers.allow_event_creation',
  CUSTOMERS_CHANGE_COLOR: 'customers.change_color',
  CUSTOMERS_EXPORT: 'customers.export',
  DASHBOARD_VIEW: 'dashboard.view',
  DASHBOARD_FINANCIAL: 'dashboard.financial',
  DASHBOARD_ALL_WORKERS: 'dashboard.all_workers',
  DASHBOARD_CONTRACTORS: 'dashboard.contractors',
  DASHBOARD_EXPORT: 'dashboard.export',
  EVENTS_VIEW: 'events.view',
  EVENTS_CREATE: 'events.create',
  EVENTS_EDIT: 'events.edit',
  EVENTS_DELETE: 'events.delete',
  EVENTS_RESTORE: 'events.restore',
  EVENTS_VIEW_DELETED: 'events.view_deleted',
  EVENTS_DUPLICATE: 'events.duplicate',
  EVENTS_IMPORT: 'events.import',
  EVENTS_EXPORT: 'events.export',
  EVENTS_CHANGE_CUSTOMER: 'events.change_customer',
  EVENTS_CHANGE_DATE: 'events.change_date',
  EVENTS_CHANGE_STATUS: 'events.change_status',
  EVENTS_MANAGE_CONTACTS: 'events.manage_contacts',
  EVENTS_VIEW_CONTACTS: 'events.view_contacts',
  EVENTS_MANAGE_SUPPLIERS: 'events.manage_suppliers',
  EVENTS_MANAGE_ADDONS: 'events.manage_addons',
  EVENTS_MANAGE_SETUP: 'events.manage_setup',
  EVENTS_EDIT_NOTES: 'events.edit_notes',
  EVENTS_ACTIVITY_LOG: 'events.activity_log',
  EVENTS_ACTIVITY_NOTE: 'events.activity_note',
  PRICING_VIEW: 'pricing.view',
  PRICING_EDIT: 'pricing.edit',
  PRICING_MANAGE_RULES: 'pricing.manage_rules',
  PRICING_REVENUE: 'pricing.revenue',
  PORTAL_VIEW: 'portal.view',
  PORTAL_ATTENDANCE: 'portal.attendance',
  PORTAL_ATTENDANCE_PAY: 'portal.attendance_pay',
  PORTAL_ASSIGN_WORKERS: 'portal.assign_workers',
  PORTAL_VIEW_FINANCIALS: 'portal.view_financials',
  PORTAL_MANAGE_WORKERS: 'portal.manage_workers',
  NOTIFICATIONS_PREFERENCES: 'notifications.preferences',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_EDIT: 'settings.edit',
  SETTINGS_TASK_TYPES: 'settings.task_types',
  SETTINGS_EXECUTION_METHODS: 'settings.execution_methods',
  SETTINGS_STATUSES: 'settings.statuses',
  SETTINGS_TRUCKS: 'settings.trucks',
  SETTINGS_RECYCLE_BIN: 'settings.recycle_bin',
  SETTINGS_AUDIT_LOG: 'settings.audit_log',
  SETTINGS_PERMISSIONS: 'settings.permissions',
  NOTIFICATIONS_VIEW: 'notifications.view',
  SEARCH_GLOBAL: 'search.global',
  TASKS_VIEW: 'tasks.view',
  TASKS_CREATE: 'tasks.create',
  TASKS_EDIT: 'tasks.edit',
  TASKS_DELETE: 'tasks.delete',
  TASKS_RESTORE: 'tasks.restore',
  TASKS_VIEW_DELETED: 'tasks.view_deleted',
  TASKS_RESCHEDULE: 'tasks.reschedule',
  TASKS_CHANGE_STATUS: 'tasks.change_status',
  TASKS_CHANGE_TYPE: 'tasks.change_type',
  TASKS_CHANGE_WORKER_COUNT: 'tasks.change_worker_count',
  TASKS_CHANGE_EXECUTION_METHOD: 'tasks.change_execution_method',
  TASKS_CHANGE_TRUCK: 'tasks.change_truck',
  TASKS_CHANGE_LOCATION: 'tasks.change_location',
  TASKS_EDIT_NOTES: 'tasks.edit_notes',
  TASKS_ASSIGN_WORKER: 'tasks.assign.worker',
  TASKS_ASSIGN_DRIVER: 'tasks.assign.driver',
  TASKS_ASSIGN_TEAM_LEAD: 'tasks.assign.team_lead',
  TASKS_ASSIGN_TRUCK: 'tasks.assign.truck',
  TASKS_ASSIGN_SELF: 'tasks.assign.self',
  TASKS_DELEGATE: 'tasks.delegate',
  TASKS_BULK_EDIT: 'tasks.bulk_edit',
  TASKS_EXPORT: 'tasks.export',
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_EDIT: 'users.edit',
  USERS_DELETE: 'users.delete',
  USERS_RESTORE: 'users.restore',
  USERS_VIEW_CONTACT: 'users.view_contact',
  USERS_MANAGE_STAFF_ROLES: 'users.manage_staff_roles',
  USERS_ASSIGN_ROLES: 'users.assign_roles',
  USERS_MANAGE_PERMISSIONS: 'users.manage_permissions',
  USERS_MANAGE_SCOPES: 'users.manage_scopes',
  USERS_CREATE_LOGIN: 'users.create_login',
  USERS_RESET_PASSWORD: 'users.reset_password',
  USERS_SET_ADMIN: 'users.set_admin',
  USERS_EXPORT: 'users.export',
} as const

export type PermissionKey = (typeof PERM)[keyof typeof PERM]
