/**
 * The permission catalog, client side.
 *
 * Keys are defined once in the database (`permission_registry`, seeded by
 * migration 0011) and mirrored here so call sites get autocompletion and a
 * compile error on a typo. The list below is generated from that table — when
 * a migration registers a new key, regenerate rather than hand-edit:
 *
 *   select key from permission_registry order by module, sort_order, key;
 *
 * Nothing breaks if this file falls behind: `has()` takes any string and the
 * server is the authority either way. The constants are ergonomics, not policy.
 */

export const PERM = {
  ATTENDANCE_VIEW_OWN: 'attendance.view_own',
  ATTENDANCE_VIEW_SCHEDULE: 'attendance.view_schedule',
  ATTENDANCE_CLOCK: 'attendance.clock',
  ATTENDANCE_SUBMIT_ENTRY: 'attendance.submit_entry',
  ATTENDANCE_APPROVE_ENTRY: 'attendance.approve_entry',
  ATTENDANCE_VIEW_OWN_PAY: 'attendance.view_own_pay',
  ATTENDANCE_VIEW_ALL: 'attendance.view_all',
  ATTENDANCE_EDIT_ENTRY: 'attendance.edit_entry',
  ATTENDANCE_MANUAL_ENTRY: 'attendance.manual_entry',
  ATTENDANCE_DELETE: 'attendance.delete',
  ATTENDANCE_MANAGE_CLOCK: 'attendance.manage_clock',
  ATTENDANCE_VIEW_PAY: 'attendance.view_pay',
  ATTENDANCE_MANAGE_PAY: 'attendance.manage_pay',
  ATTENDANCE_MANAGE_BONUS: 'attendance.manage_bonus',
  ATTENDANCE_SETTINGS: 'attendance.settings',
  ATTENDANCE_MANAGE_WAREHOUSES: 'attendance.manage_warehouses',
  ATTENDANCE_EXPORT: 'attendance.export',
  BOARD_VIEW: 'board.view',
  BOARD_VIEW_STAFFING: 'board.view_staffing',
  /* שני הכלים שמעל הלו״ז שאינם "לצפות בו": לסנן, ולפתוח כרטיס משימה. בלי
     השני, לחיצה על משימה מובילה לדף האירוע — ראו 0079. */
  BOARD_FILTER: 'board.filter',
  BOARD_OPEN_TASK: 'board.open_task',
  BOARD_INLINE_EDIT: 'board.inline_edit',
  BOARD_BULK_EDIT: 'board.bulk_edit',
  BOARD_EXPORT: 'board.export',
  BOARD_COLUMNS: 'board.columns',
  CALENDAR_VIEW: 'calendar.view',
  CALENDAR_DRAG: 'calendar.drag',
  CALENDAR_FILTER: 'calendar.filter',
  CALENDAR_SAVE_FILTERS: 'calendar.save_filters',
  CONTRACTORS_VIEW: 'contractors.view',
  CONTRACTORS_CREATE: 'contractors.create',
  CONTRACTORS_EDIT: 'contractors.edit',
  CONTRACTORS_DELETE: 'contractors.delete',
  CONTRACTORS_RESTORE: 'contractors.restore',
  CONTRACTORS_MANAGE_WORKERS: 'contractors.manage_workers',
  CONTRACTORS_VIEW_PRICING: 'contractors.view_pricing',
  CONTRACTORS_EDIT_PRICING: 'contractors.edit_pricing',
  CONTRACTORS_MARK_PAID: 'contractors.mark_paid',
  CONTRACTORS_ASSIGN_WORKERS: 'contractors.assign_workers',
  CONTRACTORS_VIEW_CONTACT: 'contractors.view_contact',
  CONTRACTORS_EXPORT: 'contractors.export',
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_EDIT: 'customers.edit',
  CUSTOMERS_DELETE: 'customers.delete',
  CUSTOMERS_RESTORE: 'customers.restore',
  CUSTOMERS_VIEW_CONTACT: 'customers.view_contact',
  CUSTOMERS_EDIT_CONTACT: 'customers.edit_contact',
  CUSTOMERS_MANAGE_FORM_FIELDS: 'customers.manage_form_fields',
  CUSTOMERS_MANAGE_EXECUTION_METHODS: 'customers.manage_execution_methods',
  CUSTOMERS_MANAGE_SUPPLIERS: 'customers.manage_suppliers',
  CUSTOMERS_ALLOW_EVENT_CREATION: 'customers.allow_event_creation',
  CUSTOMERS_CHANGE_COLOR: 'customers.change_color',
  CUSTOMERS_EXPORT: 'customers.export',
  DASHBOARD_VIEW: 'dashboard.view',
  DASHBOARD_FINANCIAL: 'dashboard.financial',
  DASHBOARD_ALL_WORKERS: 'dashboard.all_workers',
  DASHBOARD_CONTRACTORS: 'dashboard.contractors',
  DASHBOARD_EXPORT: 'dashboard.export',
  DASHBOARD_CUSTOMIZE: 'dashboard.customize',
  DASHBOARD_CONTRACTOR_COST: 'dashboard.contractor_cost',
  DASHBOARD_PAYROLL: 'dashboard.payroll',
  DASHBOARD_MARGIN: 'dashboard.margin',
  DASHBOARD_MANAGE_DEFAULT: 'dashboard.manage_default',
  DASHBOARD_BUILD_WIDGET: 'dashboard.build_widget',
  DASHBOARD_SHARE_WIDGET: 'dashboard.share_widget',
  EVENTS_VIEW: 'events.view',
  /* דף האירוע ורשימת האירועים אינם אותו מסך ואינם אותו קהל: לעובד שטח יש
     אירוע אחד לפתוח, ולא קטלוג לדפדף בו — ראו 0082. */
  EVENTS_LIST: 'events.list',
  EVENTS_CREATE: 'events.create',
  EVENTS_EDIT: 'events.edit',
  EVENTS_DELETE: 'events.delete',
  EVENTS_RESTORE: 'events.restore',
  EVENTS_VIEW_DELETED: 'events.view_deleted',
  EVENTS_DUPLICATE: 'events.duplicate',
  EVENTS_IMPORT: 'events.import',
  EVENTS_EXPORT: 'events.export',
  EVENTS_CHANGE_CUSTOMER: 'events.change_customer',
  EVENTS_CHANGE_DATE: 'events.change_date',
  EVENTS_CHANGE_STATUS: 'events.change_status',
  EVENTS_MANAGE_CONTACTS: 'events.manage_contacts',
  EVENTS_VIEW_CONTACTS: 'events.view_contacts',
  EVENTS_MANAGE_SUPPLIERS: 'events.manage_suppliers',
  EVENTS_MANAGE_ADDONS: 'events.manage_addons',
  EVENTS_MANAGE_SETUP: 'events.manage_setup',
  EVENTS_EDIT_NOTES: 'events.edit_notes',
  EVENTS_ACTIVITY_LOG: 'events.activity_log',
  EVENTS_ACTIVITY_NOTE: 'events.activity_note',
  EVENTS_ACTIVITY_NOTE_VIEW: 'events.activity_note_view',
  EVENTS_SPECS_VIEW: 'events.specs_view',
  /* העלאה והסרה נפרדו ב-0113: המפרט נולד אצל הלקוח, ולכן ההעלאה פתוחה לו
     בברירת המחדל של סוג המשתמש — וההסרה מההיסטוריה נשארה של מי שמנהל את
     האירוע. `specs_upload` נגזר מ-`specs_manage`, ולכן איש צוות שמנהל
     מפרטים ממשיך להעלות בלי שינוי. */
  EVENTS_SPECS_UPLOAD: 'events.specs_upload',
  EVENTS_SPECS_MANAGE: 'events.specs_manage',
  /* החתמת לקוח (0107). ראש צוות ההקמה והלקוח מגיעים דרך תפקיד/זהות, לא דרך
     המפתחות האלה — הם פותחים את החתימה גם לרכז משרדי שהוענק לו במפורש. */
  EVENTS_SIGN_VIEW: 'events.sign_view',
  EVENTS_SIGN_CAPTURE: 'events.sign_capture',
  FINANCE_INCOME_VIEW: 'finance.income_view',
  FINANCE_INCOME_EDIT: 'finance.income_edit',
  FINANCE_MANAGE_SPLITS: 'finance.manage_splits',
  FINANCE_RECEIPTS_VIEW: 'finance.receipts_view',
  FINANCE_RECEIPTS_MANAGE: 'finance.receipts_manage',
  /* הצד של הלקוח באותו `task_pricing.price` שאיש משרד רואה כהכנסה. מפתח
     נפרד ולא נגזר: משמעותו תלויה במי שואל, ולכן הוא ניתן ולא יורש. */
  FINANCE_CUSTOMER_SPEND: 'finance.customer_spend',
  /* צי הרכב (0089). `fleet.view` הוא מפתח שורש בכוונה — הוא אינו נגזר
     מ-`settings.trucks`, כי כרטיס הרכב מחזיק מחירי רכישה וליסינג. */
  FLEET_VIEW: 'fleet.view',
  FLEET_CREATE: 'fleet.create',
  FLEET_EDIT: 'fleet.edit',
  FLEET_DELETE: 'fleet.delete',
  FLEET_DOCS_VIEW: 'fleet.docs_view',
  FLEET_DOCS_MANAGE: 'fleet.docs_manage',
  FLEET_DRIVERS_MANAGE: 'fleet.drivers_manage',
  FLEET_VIEW_FUEL_CARD: 'fleet.view_fuel_card',
  FLEET_MANAGE_FUEL_CARD: 'fleet.manage_fuel_card',
  FLEET_SETTINGS: 'fleet.settings',
  PRICING_VIEW: 'pricing.view',
  PRICING_EDIT: 'pricing.edit',
  PRICING_MANAGE_RULES: 'pricing.manage_rules',
  PRICING_REVENUE: 'pricing.revenue',
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',
  PORTAL_VIEW: 'portal.view',
  PORTAL_ATTENDANCE: 'portal.attendance',
  PORTAL_ATTENDANCE_PAY: 'portal.attendance_pay',
  PORTAL_ASSIGN_WORKERS: 'portal.assign_workers',
  PORTAL_VIEW_FINANCIALS: 'portal.view_financials',
  PORTAL_MANAGE_WORKERS: 'portal.manage_workers',
  PORTAL_APPROVE_ATTENDANCE: 'portal.approve_attendance',
  /* הגדרות שכר ושעון לסגל של הקבלן (0103). מפתח נפרד מהמשרדי
     `attendance.manage_pay`, שמתיר לכתוב את ההגדרות של כל אדם במערכת. */
  PORTAL_WORKER_SETTINGS: 'portal.worker_settings',
  NOTIFICATIONS_PREFERENCES: 'notifications.preferences',
  NOTIFICATIONS_MANAGE: 'notifications.manage',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_EDIT: 'settings.edit',
  SETTINGS_TASK_TYPES: 'settings.task_types',
  SETTINGS_EXECUTION_METHODS: 'settings.execution_methods',
  SETTINGS_STATUSES: 'settings.statuses',
  SETTINGS_TRUCKS: 'settings.trucks',
  SETTINGS_RECYCLE_BIN: 'settings.recycle_bin',
  SETTINGS_AUDIT_LOG: 'settings.audit_log',
  SETTINGS_PERMISSIONS: 'settings.permissions',
  NOTIFICATIONS_VIEW: 'notifications.view',
  SEARCH_GLOBAL: 'search.global',
  TASKS_VIEW: 'tasks.view',
  TASKS_CREATE: 'tasks.create',
  TASKS_EDIT: 'tasks.edit',
  TASKS_DELETE: 'tasks.delete',
  TASKS_RESTORE: 'tasks.restore',
  TASKS_VIEW_DELETED: 'tasks.view_deleted',
  TASKS_RESCHEDULE: 'tasks.reschedule',
  TASKS_CHANGE_STATUS: 'tasks.change_status',
  TASKS_PUBLISH: 'tasks.publish',
  TASKS_CHANGE_TYPE: 'tasks.change_type',
  TASKS_CHANGE_WORKER_COUNT: 'tasks.change_worker_count',
  TASKS_CHANGE_EXECUTION_METHOD: 'tasks.change_execution_method',
  TASKS_CHANGE_TRUCK: 'tasks.change_truck',
  TASKS_CHANGE_LOCATION: 'tasks.change_location',
  TASKS_EDIT_NOTES: 'tasks.edit_notes',
  TASKS_ASSIGN_WORKER: 'tasks.assign.worker',
  TASKS_ASSIGN_DRIVER: 'tasks.assign.driver',
  TASKS_ASSIGN_TEAM_LEAD: 'tasks.assign.team_lead',
  TASKS_ASSIGN_TRUCK: 'tasks.assign.truck',
  TASKS_ASSIGN_SELF: 'tasks.assign.self',
  TASKS_DELEGATE: 'tasks.delegate',
  TASKS_BULK_EDIT: 'tasks.bulk_edit',
  TASKS_EXPORT: 'tasks.export',
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_EDIT: 'users.edit',
  USERS_DELETE: 'users.delete',
  USERS_RESTORE: 'users.restore',
  USERS_VIEW_CONTACT: 'users.view_contact',
  USERS_MANAGE_STAFF_ROLES: 'users.manage_staff_roles',
  USERS_ASSIGN_ROLES: 'users.assign_roles',
  USERS_MANAGE_PERMISSIONS: 'users.manage_permissions',
  USERS_MANAGE_SCOPES: 'users.manage_scopes',
  USERS_CREATE_LOGIN: 'users.create_login',
  USERS_RESET_PASSWORD: 'users.reset_password',
  USERS_SET_ADMIN: 'users.set_admin',
  USERS_EXPORT: 'users.export',
} as const

export type PermissionKey = (typeof PERM)[keyof typeof PERM]
