import {
  AlertTriangle,
  Banknote,
  Bell,
  Building2,
  Calendar,
  CalendarClock,
  CalendarDays,
  CheckCheck,
  ClipboardList,
  Clock,
  HardHat,
  History,
  ICON,
  PartyPopper,
  Percent,
  STROKE,
  Truck,
  Users,
  Wallet,
  Zap,
} from '../../components/ui/icons'
import { fmtMoney } from '../../components/ui'
import { PERM } from '../../lib/permissions'
import type { DashboardLayout, WidgetDef } from './dashboardTypes'
import { statKpi } from './widgets/kpi'
import {
  DayTimelineWidget,
  QuickActionsWidget,
  RecentListWidget,
  StatusBreakdownWidget,
  TodayListWidget,
  UpcomingListWidget,
} from './widgets/opsWidgets'
import {
  ContractorSplitWidget,
  CustomerMixWidget,
  NextEventsWidget,
  OverdueListWidget,
  TasksByCustomerWidget,
  WorkerLoadWidget,
} from './widgets/chartWidgets'
import {
  ContractorAgingWidget,
  ContractorPaidWidget,
  CostStructureWidget,
  PayrollTrendWidget,
  RevenueForecastWidget,
  ContractorCostWidget,
  ContractorUnpaidWidget,
  CostByContractorWidget,
  GrossMarginWidget,
  HoursTotalWidget,
  MarginByCustomerWidget,
  MarginTrendWidget,
  PayrollBonusWidget,
  PayrollByWorkerWidget,
  PayrollOvertimeWidget,
  PayrollTotalWidget,
  AvgPerEventWidget,
  ManualPricingShareWidget,
  RevenueByCustomerWidget,
  RevenueTrendWidget,
  UnpricedTasksWidget,
} from './widgets/financeWidgets'
import {
  AttendanceFlagsWidget,
  CustomerLeaderboardWidget,
  EventTrucksWidget,
  HeadcountWidget,
  AttendancePendingWidget,
  CustomersInactiveWidget,
  EventVolumeWidget,
  EventsByCustomerWidget,
  EventsFunnelWidget,
  FleetUtilizationWidget,
  HoursByWorkerWidget,
  NoTruckWidget,
  TasksByMethodWidget,
  TasksByTypeWidget,
  TasksTrendWidget,
  UnderstaffedWidget,
} from './widgets/sectionWidgets'
import {
  ClientShareWidget,
  FurnitureIncomeWidget,
  IncomeMixWidget,
  LogisticsIncomeWidget,
  PayrollEmployerWidget,
  ProfitSummaryWidget,
  ViperOwedWidget,
  ViperPaidWidget,
  ViperUnpaidWidget,
} from './widgets/incomeWidgets'
import {
  MyClockWidget,
  MyHoursWidget,
  MyNextShiftWidget,
  MyNotificationsWidget,
  MyPayWidget,
  MyTasksWidget,
} from './widgets/personalWidgets'

const icon = (I: typeof Clock) => <I size={ICON.md} strokeWidth={STROKE} />

/**
 * The catalogue.
 *
 * One array is the whole contract: the grid draws from it, the customise
 * drawer lists it, the merge decides what is new by looking at it, and the
 * server fan-out will read `sections` off it. Adding a widget is adding an
 * entry — nothing else has to know.
 *
 * **`id` is permanent.** It is the key a user's saved layout stores, so
 * renaming one silently relocates every dashboard in the company. Retire an
 * id rather than reuse it.
 */
export const WIDGETS: WidgetDef[] = [
  /* ── כספים ─────────────────────────────────────────────────────────────── */
  {
    id: 'finance.revenue_total',
    title: 'הכנסות בטווח',
    description: 'סך המחירים של המשימות המתומחרות בטווח, מול התקופה הקודמת',
    group: 'finance',
    icon: icon(Banknote),
    perms: [PERM.PRICING_REVENUE],
    sizes: ['sm'],
    defaultOn: true,
    usesRange: true,
    wantsDelta: true,
    Component: statKpi({
      label: 'הכנסות בטווח',
      icon: Banknote,
      tone: '#1fa189',
      delta: true,
      select: (s) => (s.revenue ? Number(s.revenue.total) : null),
      format: (v) => fmtMoney(v),
    }),
  },

  /* ── כספים: הכנסות קטגוריה, תקבולים ורווח (0068/0069) ───────────────────
     דלוקים כברירת מחדל במכוון, בניגוד למוסכמה של שאר ווידג'טי הכסף: אלה
     המדדים שהבעלים ביקש במפורש לראות על המסך כמו במערכת הישנה. מי שאין לו
     את מפתחות הכספים לא יראה אותם ממילא — הסקשן חוזר null והכרטיס מוסר. */
  {
    id: 'finance.furniture_income',
    title: 'הכנסות מריהוט',
    description: 'ריהוט ישן וחדש שהוזנו על אירועים בטווח',
    group: 'finance',
    icon: icon(Banknote),
    perms: [PERM.FINANCE_INCOME_VIEW],
    sizes: ['sm'],
    defaultOn: true,
    usesRange: true,
    wantsDelta: true,
    sections: ['income.by_category'],
    Component: FurnitureIncomeWidget,
  },
  {
    id: 'finance.logistics_income',
    title: 'הכנסות מלוגיסטיקה',
    description: 'לוגיסטיקה והובלות שהוזנו על אירועים בטווח',
    group: 'finance',
    icon: icon(Truck),
    perms: [PERM.FINANCE_INCOME_VIEW],
    sizes: ['sm'],
    defaultOn: true,
    usesRange: true,
    wantsDelta: true,
    sections: ['income.by_category'],
    Component: LogisticsIncomeWidget,
  },
  {
    id: 'finance.payroll_employer',
    title: 'משכורות עם עלות מעביד',
    description: 'עלות השכר המאושרת כפול אחוז עלות המעביד שבהגדרות',
    group: 'finance',
    icon: icon(Wallet),
    perms: [PERM.DASHBOARD_PAYROLL],
    sizes: ['sm'],
    defaultOn: true,
    usesRange: true,
    wantsDelta: true,
    sections: ['cost.payroll_employer'],
    Component: PayrollEmployerWidget,
  },
  {
    id: 'finance.viper_owed',
    title: 'סה״כ תשלום לוויפר',
    description: 'כל ההכנסות בטווח — הסכום שהלקוחות חייבים לוויפר',
    group: 'finance',
    icon: icon(Banknote),
    perms: [PERM.FINANCE_RECEIPTS_VIEW, PERM.FINANCE_INCOME_VIEW],
    sizes: ['sm'],
    defaultOn: true,
    usesRange: true,
    wantsDelta: true,
    sections: ['finance.receivables'],
    Component: ViperOwedWidget,
  },
  {
    id: 'finance.viper_paid',
    title: 'סה״כ שולם',
    description: 'סך התקבולים שנרשמו בטווח',
    group: 'finance',
    icon: icon(Banknote),
    perms: [PERM.FINANCE_RECEIPTS_VIEW, PERM.FINANCE_INCOME_VIEW],
    sizes: ['sm'],
    defaultOn: true,
    usesRange: true,
    wantsDelta: true,
    sections: ['finance.receivables'],
    Component: ViperPaidWidget,
  },
  {
    id: 'finance.viper_unpaid',
    title: 'לא שולם',
    description: 'החוב בטווח פחות התקבולים שנרשמו',
    group: 'finance',
    icon: icon(Wallet),
    perms: [PERM.FINANCE_RECEIPTS_VIEW, PERM.FINANCE_INCOME_VIEW],
    sizes: ['sm'],
    defaultOn: true,
    usesRange: true,
    wantsDelta: true,
    sections: ['finance.receivables'],
    Component: ViperUnpaidWidget,
  },
  {
    id: 'finance.client_share',
    title: 'הכנסות ללקוח',
    description: 'חלק הלקוח מהכנסות הקטגוריה, לפי האחוז שנשמר על כל אירוע',
    group: 'finance',
    icon: icon(Percent),
    perms: [PERM.FINANCE_INCOME_VIEW],
    sizes: ['sm'],
    defaultOn: true,
    usesRange: true,
    wantsDelta: true,
    sections: ['finance.client_share'],
    Component: ClientShareWidget,
  },
  {
    id: 'finance.income_mix',
    title: 'פילוח הכנסות',
    description: 'טבעת של ההכנסות לפי קטגוריה ולקוח, כולל תמחור המשימות כ"צוות"',
    group: 'finance',
    icon: icon(Percent),
    perms: [PERM.FINANCE_INCOME_VIEW, PERM.CUSTOMERS_VIEW],
    sizes: ['md', 'lg'],
    defaultOn: true,
    usesRange: true,
    sections: ['income.mix'],
    Component: IncomeMixWidget,
  },
  {
    id: 'finance.profit_summary',
    title: 'רווח',
    description: 'הכנסות פחות שכר כולל עלות מעביד ופחות קבלנים — כמו במערכת הישנה',
    group: 'finance',
    icon: icon(Percent),
    perms: [PERM.DASHBOARD_MARGIN, PERM.DASHBOARD_PAYROLL, PERM.DASHBOARD_CONTRACTOR_COST, PERM.PRICING_REVENUE],
    sizes: ['md', 'lg'],
    defaultOn: true,
    usesRange: true,
    wantsDelta: true,
    sections: ['finance.profit_summary'],
    Component: ProfitSummaryWidget,
  },

  /* ── תפעול ─────────────────────────────────────────────────────────────── */
  {
    id: 'ops.tasks_count',
    title: 'משימות בטווח',
    description: 'כמה משימות מתוזמנות בטווח התאריכים שנבחר',
    group: 'ops',
    icon: icon(ClipboardList),
    sizes: ['sm'],
    defaultOn: true,
    usesRange: true,
    wantsDelta: true,
    Component: statKpi({
      label: 'משימות בטווח',
      icon: ClipboardList,
      delta: true,
      select: (s) => s.tasks_count,
      to: '/board',
    }),
  },
  {
    id: 'ops.tasks_today',
    title: 'משימות היום',
    description: 'מונה המשימות של היום — אינו מושפע מטווח התאריכים',
    group: 'ops',
    icon: icon(Clock),
    sizes: ['sm'],
    defaultOn: true,
    Component: statKpi({ label: 'משימות היום', icon: Clock, tone: '#8b5cf6', select: (s) => s.tasks_today }),
  },
  {
    id: 'ops.tasks_week',
    title: 'משימות השבוע',
    description: 'מונה המשימות של השבוע הנוכחי',
    group: 'ops',
    icon: icon(Calendar),
    sizes: ['sm'],
    defaultOn: true,
    Component: statKpi({
      label: 'משימות השבוע',
      icon: Calendar,
      tone: '#0ea5e9',
      select: (s) => s.tasks_week,
      to: '/board',
    }),
  },
  {
    id: 'ops.tasks_overdue',
    title: 'משימות באיחור',
    description: 'משימות שתאריכן עבר והסטטוס שלהן אינו סופי',
    group: 'ops',
    icon: icon(AlertTriangle),
    sizes: ['sm'],
    defaultOn: true,
    Component: statKpi({
      label: 'משימות באיחור',
      icon: AlertTriangle,
      tone: '#ef4444',
      invertDelta: true,
      select: (s) => s.tasks_overdue,
      to: '/board',
    }),
  },
  {
    id: 'ops.day_timeline',
    title: 'ציר הזמן של היום',
    description: 'משימות היום על ציר שעות — חפיפות ופערים במבט אחד',
    group: 'ops',
    icon: icon(Clock),
    perms: [PERM.BOARD_VIEW],
    sizes: ['lg', 'xl'],
    defaultOn: true,
    Component: DayTimelineWidget,
  },
  {
    id: 'ops.by_status',
    title: 'התפלגות לפי סטטוס',
    description: 'טבעת ומקרא של המשימות בטווח, לפי סטטוס',
    group: 'ops',
    icon: icon(Zap),
    sizes: ['md', 'lg'],
    defaultOn: true,
    usesRange: true,
    Component: StatusBreakdownWidget,
  },
  {
    id: 'ops.today_list',
    title: 'משימות היום (רשימה)',
    description: 'שמונה המשימות הראשונות של היום, לפי שעה',
    group: 'ops',
    icon: icon(Clock),
    perms: [PERM.BOARD_VIEW],
    sizes: ['md', 'lg'],
    defaultOn: true,
    Component: TodayListWidget,
  },
  {
    id: 'ops.upcoming_list',
    title: 'משימות קרובות',
    description: 'שבעת הימים הבאים',
    group: 'ops',
    icon: icon(CalendarDays),
    perms: [PERM.BOARD_VIEW],
    sizes: ['md', 'lg'],
    defaultOn: true,
    Component: UpcomingListWidget,
  },
  {
    id: 'ops.recent_list',
    title: 'עודכן לאחרונה',
    description: 'שמונה השינויים האחרונים במשימות',
    group: 'ops',
    icon: icon(History),
    perms: [PERM.BOARD_VIEW],
    sizes: ['md', 'lg'],
    defaultOn: true,
    Component: RecentListWidget,
  },
  {
    id: 'cust.tasks_by_customer',
    title: 'משימות לפי לקוח',
    description: 'עמודות בצבע הלקוח, שנים־עשר המובילים',
    group: 'customers',
    icon: icon(ClipboardList),
    perms: [PERM.CUSTOMERS_VIEW],
    sizes: ['md', 'lg'],
    defaultOn: true,
    usesRange: true,
    Component: TasksByCustomerWidget,
  },

  /* ── לקוחות ────────────────────────────────────────────────────────────── */
  {
    id: 'cust.events_count',
    title: 'אירועים בטווח',
    description: 'כמה אירועים בטווח התאריכים שנבחר, מול התקופה הקודמת',
    group: 'customers',
    icon: icon(CalendarDays),
    sizes: ['sm'],
    defaultOn: true,
    usesRange: true,
    wantsDelta: true,
    Component: statKpi({
      label: 'אירועים בטווח',
      icon: CalendarDays,
      delta: true,
      select: (s) => s.events_count,
      to: '/events',
    }),
  },
  {
    id: 'cust.next_events',
    title: 'האירועים הקרובים',
    description: 'חמשת האירועים הבאים — מה שכבר הוזמן, להבדיל ממה שקורה היום',
    group: 'customers',
    icon: icon(PartyPopper),
    sizes: ['md', 'lg', 'xl'],
    defaultOn: true,
    Component: NextEventsWidget,
  },

  /* ── כוח אדם ───────────────────────────────────────────────────────────── */
  {
    id: 'hr.available_workers',
    title: 'עובדים זמינים היום',
    description: 'עובדי צוות פעילים שאין להם שיבוץ היום',
    group: 'people',
    icon: icon(Users),
    perms: [PERM.DASHBOARD_ALL_WORKERS],
    sizes: ['sm'],
    defaultOn: true,
    Component: statKpi({
      label: 'עובדים זמינים היום',
      icon: Users,
      tone: '#22c55e',
      select: (s) => s.available_workers,
      to: '/users',
    }),
  },
  {
    id: 'hr.workload',
    title: 'עומס עובדים',
    description: 'כמה שיבוצים יש לכל עובד בטווח',
    group: 'people',
    icon: icon(Users),
    perms: [PERM.DASHBOARD_ALL_WORKERS],
    sizes: ['md', 'lg'],
    defaultOn: true,
    usesRange: true,
    Component: WorkerLoadWidget,
  },
  {
    id: 'hr.contractor_split',
    title: 'התפלגות קבלנים',
    description: 'כמה משימות הואצלו לכל קבלן בטווח',
    group: 'people',
    icon: icon(Users),
    perms: [PERM.DASHBOARD_CONTRACTORS],
    sizes: ['md', 'lg'],
    defaultOn: true,
    usesRange: true,
    Component: ContractorSplitWidget,
  },

  /* ── אישי ──────────────────────────────────────────────────────────────── */
  {
    id: 'me.quick_actions',
    title: 'פעולות מהירות',
    description: 'אירוע חדש, משימה חדשה, ומעבר ללוחות',
    group: 'me',
    icon: icon(Zap),
    sizes: ['xl'],
    defaultOn: true,
    Component: QuickActionsWidget,
  },

  /* ── כספים: מה שהיה חסר ─────────────────────────────────────────────────
     כולם כבויים כברירת מחדל. מפתח חדש שנוחת דלוק היה משנה לאנשים את המסך
     בלי שביקשו, ובמקרה של כסף גם היה מציג להם מספרים שלא ציפו להם. */
  {
    id: 'finance.revenue_by_customer',
    title: 'הכנסות לפי לקוח',
    description: 'סך ההכנסות מכל לקוח בטווח, בצבע שלו',
    group: 'finance',
    icon: icon(Banknote),
    perms: [PERM.PRICING_REVENUE, PERM.CUSTOMERS_VIEW],
    sizes: ['md', 'lg', 'xl'],
    usesRange: true,
    Component: RevenueByCustomerWidget,
  },
  {
    id: 'finance.revenue_trend',
    title: 'מגמת הכנסות',
    description: 'הכנסות לאורך זמן — יום, שבוע או חודש',
    group: 'finance',
    icon: icon(Banknote),
    perms: [PERM.PRICING_REVENUE],
    sizes: ['md', 'lg', 'xl'],
    usesRange: true,
    sections: ['revenue.trend'],
    Component: RevenueTrendWidget,
  },
  {
    id: 'finance.unpriced_tasks',
    title: 'משימות ללא תמחור',
    description: 'משימות שאינן נספרות בסך ההכנסות — דליפת הכנסה שקטה',
    group: 'finance',
    icon: icon(AlertTriangle),
    perms: [PERM.PRICING_VIEW],
    sizes: ['sm'],
    usesRange: true,
    sections: ['pricing.quality'],
    Component: UnpricedTasksWidget,
  },
  {
    id: 'finance.contractor_cost',
    title: 'עלות קבלנים',
    description: 'הסכום שסוכם עם הקבלנים על משימות בטווח',
    group: 'finance',
    icon: icon(HardHat),
    perms: [PERM.DASHBOARD_CONTRACTOR_COST],
    sizes: ['sm'],
    usesRange: true,
    wantsDelta: true,
    sections: ['cost.contractor'],
    Component: ContractorCostWidget,
  },
  {
    id: 'finance.contractor_unpaid',
    title: 'יתרה לקבלנים',
    description: 'מה שסוכם ועדיין לא שולם',
    group: 'finance',
    icon: icon(Wallet),
    perms: [PERM.DASHBOARD_CONTRACTOR_COST],
    sizes: ['sm'],
    usesRange: true,
    wantsDelta: true,
    sections: ['cost.contractor'],
    Component: ContractorUnpaidWidget,
  },
  {
    id: 'finance.contractor_aging',
    title: 'יתרה לקבלנים לפי התיישנות',
    description: 'כמה מהחוב הוא עד 30 יום, כמה 31–60 וכמה מעל',
    group: 'finance',
    icon: icon(Wallet),
    perms: [PERM.DASHBOARD_CONTRACTOR_COST],
    sizes: ['md', 'lg'],
    usesRange: true,
    sections: ['cost.contractor'],
    Component: ContractorAgingWidget,
  },
  {
    id: 'finance.cost_by_contractor',
    title: 'עלות לפי קבלן',
    description: 'מחויב מול ששולם, לכל קבלן',
    group: 'finance',
    icon: icon(HardHat),
    perms: [PERM.DASHBOARD_CONTRACTOR_COST, PERM.CONTRACTORS_VIEW],
    sizes: ['md', 'lg'],
    usesRange: true,
    sections: ['cost.by_contractor'],
    Component: CostByContractorWidget,
  },
  {
    id: 'finance.payroll_total',
    title: 'עלות שכר',
    description: 'עלות השכר בטווח — משמרות מאושרות בלבד',
    group: 'finance',
    icon: icon(Wallet),
    perms: [PERM.DASHBOARD_PAYROLL],
    sizes: ['sm'],
    usesRange: true,
    wantsDelta: true,
    sections: ['cost.payroll'],
    Component: PayrollTotalWidget,
  },
  {
    id: 'finance.payroll_overtime',
    title: 'שעות נוספות',
    description: 'כמה מהשעות בטווח הן שעות נוספות',
    group: 'finance',
    icon: icon(AlertTriangle),
    perms: [PERM.DASHBOARD_PAYROLL],
    sizes: ['sm'],
    usesRange: true,
    sections: ['cost.payroll'],
    Component: PayrollOvertimeWidget,
  },
  {
    id: 'finance.payroll_bonus',
    title: 'בונוסים',
    description: 'סכומי הבונוס למשמרות בטווח',
    group: 'finance',
    icon: icon(Banknote),
    perms: [PERM.DASHBOARD_PAYROLL],
    sizes: ['sm'],
    usesRange: true,
    sections: ['cost.payroll'],
    Component: PayrollBonusWidget,
  },
  {
    id: 'finance.payroll_by_worker',
    title: 'עלות שכר לפי עובד',
    description: 'הפירוק האישי — דורש גם הרשאת סטטיסטיקות עובדים',
    group: 'finance',
    icon: icon(Users),
    perms: [PERM.DASHBOARD_PAYROLL, PERM.DASHBOARD_ALL_WORKERS],
    sizes: ['md', 'lg'],
    usesRange: true,
    sections: ['cost.payroll_by_worker'],
    Component: PayrollByWorkerWidget,
  },
  {
    id: 'finance.gross_margin',
    title: 'רווח גולמי',
    description: 'הכנסות פחות עלות קבלנים ועלות שכר. אינו כולל תקורה',
    group: 'finance',
    icon: icon(Percent),
    perms: [PERM.DASHBOARD_MARGIN, PERM.DASHBOARD_PAYROLL, PERM.DASHBOARD_CONTRACTOR_COST, PERM.PRICING_REVENUE],
    sizes: ['md', 'lg'],
    usesRange: true,
    wantsDelta: true,
    sections: ['margin.summary'],
    Component: GrossMarginWidget,
  },
  {
    id: 'finance.margin_trend',
    title: 'הכנסות מול עלויות לאורך זמן',
    description: 'עמודות מוערמות של הכנסה ועלויות, עם קו הרווח הגולמי',
    group: 'finance',
    icon: icon(Percent),
    perms: [PERM.DASHBOARD_MARGIN, PERM.DASHBOARD_PAYROLL, PERM.DASHBOARD_CONTRACTOR_COST, PERM.PRICING_REVENUE],
    sizes: ['lg', 'xl'],
    usesRange: true,
    sections: ['margin.trend'],
    Component: MarginTrendWidget,
  },
  {
    id: 'finance.margin_by_customer',
    title: 'רווח גולמי לפי לקוח',
    description: 'הכנסה, עלויות ורווח לכל לקוח. עלות השכר מוקצית לפי שעות — הערכה',
    group: 'finance',
    icon: icon(Percent),
    perms: [
      PERM.DASHBOARD_MARGIN,
      PERM.DASHBOARD_PAYROLL,
      PERM.DASHBOARD_CONTRACTOR_COST,
      PERM.PRICING_REVENUE,
      PERM.CUSTOMERS_VIEW,
    ],
    sizes: ['lg', 'xl'],
    usesRange: true,
    sections: ['margin.by_customer'],
    Component: MarginByCustomerWidget,
  },

  /* ── תפעול: עומק ────────────────────────────────────────────────────── */
  {
    id: 'ops.by_type',
    title: 'משימות לפי סוג',
    description: 'התפלגות המשימות בטווח לפי סוג משימה',
    group: 'ops',
    icon: icon(ClipboardList),
    sizes: ['md', 'lg'],
    usesRange: true,
    sections: ['tasks.by_type'],
    Component: TasksByTypeWidget,
  },
  {
    id: 'ops.by_method',
    title: 'משימות לפי אופן ביצוע',
    description: 'סידור, הרכבה, הובלה — מה מהם ממלא את הטווח',
    group: 'ops',
    icon: icon(ClipboardList),
    sizes: ['md', 'lg'],
    usesRange: true,
    sections: ['tasks.by_method'],
    Component: TasksByMethodWidget,
  },
  {
    id: 'ops.trend',
    title: 'מגמת משימות ואירועים',
    description: 'שני קווים לאורך זמן — יום, שבוע או חודש',
    group: 'ops',
    icon: icon(ClipboardList),
    sizes: ['md', 'lg', 'xl'],
    usesRange: true,
    sections: ['tasks.trend'],
    Component: TasksTrendWidget,
  },
  {
    id: 'ops.understaffed',
    title: 'משימות בתת-איוש',
    description: 'משימות פתוחות שמשובצים אליהן פחות עובדים ממה שנדרש',
    group: 'ops',
    icon: icon(Users),
    anyPerms: [PERM.DASHBOARD_ALL_WORKERS, PERM.TASKS_ASSIGN_WORKER],
    sizes: ['md', 'lg'],
    usesRange: true,
    sections: ['tasks.understaffed'],
    Component: UnderstaffedWidget,
  },
  {
    id: 'ops.no_truck',
    title: 'משימות ללא משאית',
    description: 'משימות פתוחות בלי משאית משובצת ובלי טקסט חופשי',
    group: 'ops',
    icon: icon(Truck),
    sizes: ['sm'],
    usesRange: true,
    sections: ['tasks.no_truck'],
    Component: NoTruckWidget,
  },
  {
    id: 'ops.fleet_utilization',
    title: 'ניצולת משאיות',
    description: 'בכמה ימים בטווח עבדה כל משאית',
    group: 'ops',
    icon: icon(Truck),
    sizes: ['md', 'lg'],
    usesRange: true,
    sections: ['fleet.utilization'],
    Component: FleetUtilizationWidget,
  },

  /* ── לקוחות ─────────────────────────────────────────────────────────── */
  {
    id: 'cust.events_by_customer',
    title: 'כמות אירועים לפי לקוח',
    description: 'כמה אירועים לכל לקוח בטווח',
    group: 'customers',
    icon: icon(PartyPopper),
    perms: [PERM.CUSTOMERS_VIEW],
    sizes: ['md', 'lg'],
    usesRange: true,
    sections: ['events.by_customer'],
    Component: EventsByCustomerWidget,
  },
  {
    id: 'cust.events_funnel',
    title: 'אירועים לפי סטטוס',
    description: 'טרם אושר, אישור סופי, מתקיים, בוטל',
    group: 'customers',
    icon: icon(PartyPopper),
    sizes: ['md', 'lg'],
    usesRange: true,
    sections: ['events.funnel'],
    Component: EventsFunnelWidget,
  },
  {
    id: 'cust.event_volume',
    title: 'נפח מטען',
    description: 'סך המ״ק והמשאיות שהאירועים בטווח דורשים',
    group: 'customers',
    icon: icon(Truck),
    perms: [PERM.CUSTOMERS_VIEW],
    sizes: ['sm'],
    usesRange: true,
    sections: ['events.volume'],
    Component: EventVolumeWidget,
  },
  {
    id: 'cust.inactive',
    title: 'לקוחות ללא פעילות',
    description: 'לקוחות פעילים שאין להם אירוע בטווח שנבחר',
    group: 'customers',
    icon: icon(Building2),
    perms: [PERM.CUSTOMERS_VIEW],
    sizes: ['md', 'lg'],
    usesRange: true,
    sections: ['customers.inactive'],
    Component: CustomersInactiveWidget,
  },

  /* ── כוח אדם ────────────────────────────────────────────────────────── */
  {
    id: 'hr.hours_total',
    title: 'שעות עבודה בטווח',
    description: 'שעות מאושרות — בלי כסף, כדי שרכז משמרות יוכל לראות עומס',
    group: 'people',
    icon: icon(Clock),
    perms: [PERM.ATTENDANCE_VIEW_ALL],
    sizes: ['sm'],
    usesRange: true,
    wantsDelta: true,
    sections: ['attendance.hours'],
    Component: HoursTotalWidget,
  },
  {
    id: 'hr.hours_by_worker',
    title: 'שעות לפי עובד',
    description: 'כמה שעות מאושרות לכל עובד בטווח',
    group: 'people',
    icon: icon(Users),
    perms: [PERM.ATTENDANCE_VIEW_ALL],
    sizes: ['md', 'lg'],
    usesRange: true,
    sections: ['attendance.hours_by_worker'],
    Component: HoursByWorkerWidget,
  },
  {
    id: 'hr.attendance_pending',
    title: 'דיווחי נוכחות לאישור',
    description: 'משמרות שעובדים דיווחו ידנית וממתינות להכרעה',
    group: 'people',
    icon: icon(CheckCheck),
    perms: [PERM.ATTENDANCE_APPROVE_ENTRY],
    sizes: ['md', 'lg'],
    sections: ['attendance.pending'],
    Component: AttendancePendingWidget,
  },
  {
    id: 'hr.attendance_flags',
    title: 'חריגות נוכחות',
    description: 'החתמות מחוץ לרדיוס, בלי קואורדינטות, או שנסגרו אוטומטית',
    group: 'people',
    icon: icon(AlertTriangle),
    perms: [PERM.ATTENDANCE_VIEW_ALL],
    sizes: ['md', 'lg'],
    usesRange: true,
    sections: ['attendance.flags'],
    Component: AttendanceFlagsWidget,
  },

  /* ── מונים נוספים מ-dashboard_stats ────────────────────────────────────
     הנתון כבר הגיע מהשרת מאז 0026 ופשוט לא צויר. */
  {
    id: 'ops.tasks_open',
    title: 'משימות פתוחות',
    description: 'משימות בטווח שהסטטוס שלהן אינו סופי',
    group: 'ops',
    icon: icon(ClipboardList),
    sizes: ['sm'],
    usesRange: true,
    wantsDelta: true,
    Component: statKpi({
      label: 'משימות פתוחות',
      icon: ClipboardList,
      tone: '#0ea5e9',
      delta: true,
      select: (s) => s.tasks_open,
      to: '/board',
    }),
  },
  {
    id: 'cust.events_upcoming',
    title: 'אירועים עתידיים',
    description: 'אירועים מהיום והלאה שטרם הסתיימו — אינו מושפע מהטווח',
    group: 'customers',
    icon: icon(PartyPopper),
    sizes: ['sm'],
    Component: statKpi({
      label: 'אירועים עתידיים',
      icon: PartyPopper,
      tone: '#1fa189',
      select: (s) => s.events_upcoming,
      to: '/events',
    }),
  },
  {
    id: 'cust.events_done',
    title: 'אירועים שהסתיימו',
    description: 'אירועים בטווח שהגיעו לסטטוס סופי',
    group: 'customers',
    icon: icon(CheckCheck),
    sizes: ['sm'],
    usesRange: true,
    wantsDelta: true,
    Component: statKpi({
      label: 'אירועים שהסתיימו',
      icon: CheckCheck,
      tone: '#22c55e',
      delta: true,
      select: (s) => s.events_done,
    }),
  },
  {
    id: 'finance.contractor_paid',
    title: 'שולם לקבלנים',
    description: 'מה שכבר שולם מתוך מה שסוכם',
    group: 'finance',
    icon: icon(Banknote),
    perms: [PERM.DASHBOARD_CONTRACTOR_COST],
    sizes: ['sm'],
    usesRange: true,
    sections: ['cost.contractor'],
    Component: ContractorPaidWidget,
  },
  {
    id: 'finance.payroll_trend',
    title: 'מגמת עלות שכר',
    description: 'עלות השכר לאורך זמן — יום, שבוע או חודש',
    group: 'finance',
    icon: icon(Wallet),
    perms: [PERM.DASHBOARD_PAYROLL],
    sizes: ['md', 'lg', 'xl'],
    usesRange: true,
    sections: ['cost.payroll_trend'],
    Component: PayrollTrendWidget,
  },
  {
    id: 'finance.cost_structure',
    title: 'הרכב עלות ישירה',
    description: 'איך מתחלקת העלות בין קבלנים לשכר',
    group: 'finance',
    icon: icon(Percent),
    perms: [PERM.DASHBOARD_MARGIN, PERM.DASHBOARD_PAYROLL, PERM.DASHBOARD_CONTRACTOR_COST, PERM.PRICING_REVENUE],
    sizes: ['md'],
    usesRange: true,
    sections: ['margin.summary'],
    Component: CostStructureWidget,
  },
  {
    id: 'finance.revenue_forecast',
    title: 'תחזית הכנסות',
    description: 'משימות עתידיות שכבר מתומחרות — אינו מושפע מהטווח',
    group: 'finance',
    icon: icon(Banknote),
    perms: [PERM.PRICING_REVENUE],
    sizes: ['sm'],
    sections: ['revenue.forecast'],
    Component: RevenueForecastWidget,
  },
  {
    id: 'cust.leaderboard',
    title: 'לקוחות מובילים',
    description: 'אירועים, משימות והכנסה לכל לקוח, בטבלה אחת',
    group: 'customers',
    icon: icon(Building2),
    perms: [PERM.CUSTOMERS_VIEW],
    sizes: ['lg', 'xl'],
    usesRange: true,
    sections: ['customers.leaderboard'],
    Component: CustomerLeaderboardWidget,
  },
  {
    id: 'hr.headcount',
    title: 'סגל פעיל',
    description: 'כמה חשבונות פעילים יש, ומתוכם כמה עובדי צוות',
    group: 'people',
    icon: icon(Users),
    perms: [PERM.DASHBOARD_ALL_WORKERS],
    sizes: ['sm'],
    sections: ['hr.headcount'],
    Component: HeadcountWidget,
  },

  /* ── אישי ───────────────────────────────────────────────────────────────
     הקבוצה היחידה שעובד מן השורה רואה ממנה משהו. הכול נשען על הוקים שכבר
     קיימים במסכים שמהם הנתון הגיע. */
  {
    id: 'me.my_tasks',
    title: 'המשימות שלי',
    description: 'משימות מהיום והלאה ששובצת אליהן',
    group: 'me',
    icon: icon(ClipboardList),
    perms: [PERM.TASKS_VIEW],
    sizes: ['md', 'lg'],
    Component: MyTasksWidget,
  },
  {
    id: 'me.next_shift',
    title: 'המשמרות הקרובות שלי',
    description: 'המשמרות שנגזרות מהמשימות ששובצת אליהן, שבועיים קדימה',
    group: 'me',
    icon: icon(CalendarClock),
    perms: [PERM.ATTENDANCE_VIEW_SCHEDULE],
    sizes: ['md', 'lg'],
    Component: MyNextShiftWidget,
  },
  {
    id: 'me.clock',
    title: 'שעון נוכחות',
    description: 'האם אתה במשמרת כרגע, ומאיזו שעה',
    group: 'me',
    icon: icon(Clock),
    perms: [PERM.ATTENDANCE_VIEW_OWN],
    sizes: ['sm'],
    Component: MyClockWidget,
  },
  {
    id: 'me.my_hours',
    title: 'השעות שלי',
    description: 'שעות מאושרות בטווח שנבחר',
    group: 'me',
    icon: icon(Clock),
    perms: [PERM.ATTENDANCE_VIEW_OWN],
    sizes: ['sm'],
    usesRange: true,
    Component: MyHoursWidget,
  },
  {
    id: 'me.my_pay',
    title: 'השכר שלי',
    description: 'השכר על משמרות מאושרות בטווח',
    group: 'me',
    icon: icon(Wallet),
    perms: [PERM.ATTENDANCE_VIEW_OWN_PAY],
    sizes: ['sm'],
    usesRange: true,
    Component: MyPayWidget,
  },
  {
    id: 'me.notifications',
    title: 'ההתראות שלי',
    description: 'חמש ההתראות האחרונות ומונה מה שלא נקרא',
    group: 'me',
    icon: icon(Bell),
    perms: [PERM.NOTIFICATIONS_VIEW],
    sizes: ['md', 'lg'],
    Component: MyNotificationsWidget,
  },

  {
    id: 'finance.avg_per_event',
    title: 'הכנסה ממוצעת לאירוע',
    description: 'סך ההכנסות בטווח חלקי מספר האירועים',
    group: 'finance',
    icon: icon(Banknote),
    perms: [PERM.PRICING_REVENUE],
    sizes: ['sm'],
    usesRange: true,
    Component: AvgPerEventWidget,
  },
  {
    id: 'finance.manual_pricing_share',
    title: 'תמחור ידני מול אוטומטי',
    description: 'כמה מהמשימות תומחרו במחשבון וכמה נקבעו ביד',
    group: 'finance',
    icon: icon(Percent),
    perms: [PERM.PRICING_VIEW],
    sizes: ['md'],
    usesRange: true,
    sections: ['pricing.quality'],
    Component: ManualPricingShareWidget,
  },
  {
    id: 'ops.overdue_list',
    title: 'רשימת האיחורים',
    description: 'המשימות שתאריכן עבר והסטטוס שלהן אינו סופי',
    group: 'ops',
    icon: icon(AlertTriangle),
    perms: [PERM.BOARD_VIEW],
    sizes: ['md', 'lg'],
    Component: OverdueListWidget,
  },
  {
    id: 'cust.customer_mix',
    title: 'תמהיל לקוחות',
    description: 'כמה מההכנסות נשענות על הלקוח הגדול ביותר',
    group: 'customers',
    icon: icon(Percent),
    perms: [PERM.CUSTOMERS_VIEW, PERM.PRICING_REVENUE],
    sizes: ['md', 'lg'],
    usesRange: true,
    Component: CustomerMixWidget,
  },
  {
    id: 'cust.event_trucks',
    title: 'משאיות נדרשות',
    description: 'סך המשאיות שהאירועים בטווח דורשים',
    group: 'customers',
    icon: icon(Truck),
    perms: [PERM.CUSTOMERS_VIEW],
    sizes: ['sm'],
    usesRange: true,
    sections: ['events.volume'],
    Component: EventTrucksWidget,
  },
]

export const WIDGETS_BY_ID = new Map(WIDGETS.map((w) => [w.id, w]))
export const WIDGET_IDS = new Set(WIDGETS.map((w) => w.id))

/**
 * The layout a user with nothing saved gets, and the layout the "reset" button
 * returns to.
 *
 * The order below reproduces the pre-widget dashboard exactly — KPI row, quick
 * actions, timeline beside the status donut, upcoming events, the three task
 * lists, the three charts. That is the point of it: turning the page into
 * widgets is not supposed to be a redesign, and anything that moved would be a
 * change nobody asked for.
 *
 * Every `defaultOn` widget must appear here. One that does not would be
 * re-added by `resolveLayout` on every single load — `registry.test.ts` holds
 * that invariant.
 */
export const BUILT_IN_DEFAULT: DashboardLayout = {
  v: 1,
  items: [
    { id: 'cust.events_count', size: 'sm' },
    { id: 'ops.tasks_count', size: 'sm' },
    { id: 'ops.tasks_today', size: 'sm' },
    { id: 'ops.tasks_week', size: 'sm' },
    { id: 'ops.tasks_overdue', size: 'sm' },
    { id: 'hr.available_workers', size: 'sm' },
    { id: 'finance.revenue_total', size: 'sm' },

    /* שורת הכספים של המערכת הישנה (0068/0069) */
    { id: 'finance.furniture_income', size: 'sm' },
    { id: 'finance.logistics_income', size: 'sm' },
    { id: 'finance.payroll_employer', size: 'sm' },
    { id: 'finance.viper_owed', size: 'sm' },
    { id: 'finance.viper_paid', size: 'sm' },
    { id: 'finance.viper_unpaid', size: 'sm' },
    { id: 'finance.client_share', size: 'sm' },

    { id: 'me.quick_actions', size: 'xl' },

    { id: 'ops.day_timeline', size: 'lg' },
    { id: 'ops.by_status', size: 'md' },

    { id: 'cust.next_events', size: 'xl' },

    { id: 'ops.today_list', size: 'md' },
    { id: 'ops.upcoming_list', size: 'md' },
    { id: 'ops.recent_list', size: 'md' },

    { id: 'cust.tasks_by_customer', size: 'md' },
    { id: 'hr.workload', size: 'md' },
    { id: 'hr.contractor_split', size: 'md' },

    { id: 'finance.income_mix', size: 'md' },
    { id: 'finance.profit_summary', size: 'md' },
  ],
  hidden: [],
  seen: WIDGETS.map((w) => w.id),
}
